version: '2'

services:
    web:
        build: ./
        ports:
            - "8080:80"
        networks:
            - code-network
    php:
        build: ./php
        networks:
            - code-network

networks:
    code-network:
        driver: bridge